# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest')], max_length=2)),
                ('section', models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('learn', models.TextField()),
                ('act1', models.TextField()),
                ('act2', models.TextField()),
                ('share', models.TextField()),
                ('share_has_textarea', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act1', models.TextField()),
                ('act2', models.TextField()),
                ('share', models.TextField()),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.CharField(max_length=30)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbook.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbook.Profile'),
        ),
    ]
