# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0003_auto_20160402_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest')], default='d', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='office',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest')], default='d', max_length=2),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='section',
            field=models.CharField(choices=[('ss', 'Spiritual Strength'), ('pd', 'Priesthood Duties'), ('ftsoy', 'For The Strenght Of Youth'), ('mp', 'Preparing To Receive the Melchizedek Priesthood')], default='ss', max_length=5),
        ),
    ]
