# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0004_auto_20160408_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personprogress',
            options={'verbose_name_plural': 'person progress records'},
        ),
        migrations.AlterField(
            model_name='personprogress',
            name='act2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personprogress',
            name='share',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personprogress',
            name='shared_with',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
