# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0005_auto_20160416_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='John', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Doe', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='1111111111', help_text='Phone number for identifying your account', max_length=10, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_text_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ward or branch'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='office',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest'), ('-', 'Leader, Bishop, Advisor')], default='d', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest'), ('-', 'Leader, Bishop, Advisor')], max_length=2),
        ),
        migrations.AddField(
            model_name='profilenotify',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbook.Profile'),
        ),
    ]
