# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0006_auto_20160528_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
