# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0007_auto_20160704_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='footnote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='office',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest'), ('-', 'Leader, Bishop, or Advisor')], default='d', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('p', 'Priest'), ('-', 'Leader, Bishop, or Advisor')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='personprogress',
            unique_together=set([('profile', 'assignment')]),
        ),
    ]
