# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0012_personprogress_review_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprogress',
            name='review_requested_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.ProfileNotify'),
        ),
        migrations.AlterField(
            model_name='personprogress',
            name='shared_with',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
