# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0013_auto_20160827_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNotifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, max_length=50, null=True, verbose_name='ward or branch')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['stake', 'ward'],
            },
        ),
        migrations.AddField(
            model_name='defaultnotifier',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbook.Unit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workbook.Unit'),
            preserve_default=False,
        ),
    ]
