# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-30 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0014_auto_20161029_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultnotifier',
            name='show_to',
            field=models.CharField(choices=[('d', 'Deacon'), ('t', 'Teacher'), ('z', 'Priest'), ('-', 'All Young Men')], default='-', max_length=2),
        ),
        migrations.AddField(
            model_name='profilenotify',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workbook.Unit'),
            preserve_default=False,
        ),
    ]
