# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0020_auto_20161120_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultnotifier',
            name='show_to',
            field=models.CharField(choices=[('d', 'Deacons Only'), ('t', 'Teachers Only'), ('z', 'Priests Only'), ('-', 'All Young Men')], default='-', max_length=2),
        ),
    ]
